// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Thermostat_Controller

#ifndef _THERMOSTAT_CONTROLLER_UI_H
#define _THERMOSTAT_CONTROLLER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "ui_Main.h"
#include "ui_SettingsScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_flame_off_png);    // assets/flame_off.png
LV_IMG_DECLARE(ui_img_down_arrow_png);    // assets/down_arrow.png
LV_IMG_DECLARE(ui_img_up_arrow_png);    // assets/up_arrow.png
LV_IMG_DECLARE(ui_img_wifi_off_png);    // assets/wifi_off.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_flame_png);    // assets/flame.png
LV_IMG_DECLARE(ui_img_gear_png);    // assets/gear.png

// FONTS
LV_FONT_DECLARE(ui_font_Ubuntu_Bold_180);
LV_FONT_DECLARE(ui_font_Ubuntu_Bold__45);
LV_FONT_DECLARE(ui_font_Ubuntu_Bold__75);
LV_FONT_DECLARE(ui_font_Ubuntu_Regular_45);
LV_FONT_DECLARE(ui_font_Ubuntu_Regular__20);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
