// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Thermostat_Controller

#include "ui.h"

void downTempPressed(lv_event_t * e)
{
	// Your code here
}

void downTempLongPressed(lv_event_t * e)
{
	// Your code here
}

void upTempPressed(lv_event_t * e)
{
	// Your code here
}

void upTempLongPressed(lv_event_t * e)
{
	// Your code here
}
