// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Thermostat_Controller

#include <Arduino.h>
#include "ui.h"
#include "configuration.h"
#include <lvgl.h>

void incrementSetTemp(uint8_t delta, lv_obj_t *obj)
{
	DeviceConfig *config = currentDeviceConfig();
	if (!config->heatEnabled)
	{
		return;
	}

	// The UI must be update here because dirty isn't set until the button is released. Using
	config->setTemp += delta;
	config->setTemp = constrain(config->setTemp, 0, 99);
	lv_label_set_text_fmt(ui_SetTemperature, "%i", config->setTemp);

	lv_obj_set_style_opa(obj, LV_OPA_30, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void setTempFinished(lv_obj_t *obj)
{
	DeviceConfig *config = currentDeviceConfig();
	if (!config->heatEnabled)
	{
		return;
	}

	config->dirty = true;

	lv_obj_set_style_opa(obj, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
}	

void downTempEvent(lv_event_t *e)
{
	incrementSetTemp(-1, ui_DownArrow);
}

void upTempEvent(lv_event_t *e)
{
	incrementSetTemp(1, ui_UpArrow);
}

void upTempEventFinished(lv_event_t *e)
{
	setTempFinished(ui_UpArrow);
}

void downTempEventFinished(lv_event_t *e)
{
	setTempFinished(ui_DownArrow);
}

void heatValueChanged(lv_event_t *e)
{
	lv_obj_t *switch_obj = (lv_obj_t *)lv_event_get_target(e);

	DeviceConfig *config = currentDeviceConfig();
	config->heatEnabled = lv_obj_has_state(switch_obj, LV_STATE_CHECKED);
	config->dirty = true;
}

void initializeSettingsScreen(lv_event_t *e)
{
	DeviceConfig *config = currentDeviceConfig();

	lv_obj_set_state(ui_HeatOnSwitch, LV_STATE_CHECKED, config->heatEnabled);
	lv_dropdown_set_selected(ui_HysteresisDropdown, config->hysteresis);
	lv_label_set_text(ui_WiFiValue, config->wifiSsid);
}

void hytersisValueChanged(lv_event_t *e)
{
	lv_obj_t *dropdown_obj = (lv_obj_t *)lv_event_get_target(e);

	uint32_t selectedIndex = lv_dropdown_get_selected(dropdown_obj);

	DeviceConfig *config = currentDeviceConfig();
	config->hysteresis = selectedIndex;
	config->dirty = true;
}
