// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Thermostat_Controller

#include "ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_Temperature = NULL;
lv_obj_t * ui_Humidity = NULL;
lv_obj_t * ui_Heating = NULL;
lv_obj_t * ui_Flame = NULL;
lv_obj_t * ui_Main_Seperator = NULL;
lv_obj_t * ui_Set_Temperature = NULL;
lv_obj_t * ui_Down_Arrow = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Temperature_F = NULL;
lv_obj_t * ui_Set_Temperature_F = NULL;
lv_obj_t * ui_Up_Arrow = NULL;
lv_obj_t * ui_WiFi_Off = NULL;
lv_obj_t * ui_Wifi_On = NULL;
lv_obj_t * ui_Flame_On = NULL;
// event funtions
void ui_event_Down_Arrow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        downTempPressed(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        downTempLongPressed(e);
    }
}

void ui_event_Up_Arrow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        upTempPressed(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        upTempLongPressed(e);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x15233D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature, -125);
    lv_obj_set_y(ui_Temperature, -44);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature, "72");
    ui_object_set_themeable_style_property(ui_Temperature, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Primary);
    ui_object_set_themeable_style_property(ui_Temperature, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Primary);
    lv_obj_set_style_text_font(ui_Temperature, &ui_font_Ubuntu_Bold_180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidity, -109);
    lv_obj_set_y(ui_Humidity, 38);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humidity, "32% Humidity");
    ui_object_set_themeable_style_property(ui_Humidity, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Primary);
    ui_object_set_themeable_style_property(ui_Humidity, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Primary);
    lv_obj_set_style_text_font(ui_Humidity, &ui_font_Ubuntu_Bold__45, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Heating = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Heating, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Heating, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Heating, -101);
    lv_obj_set_y(ui_Heating, 124);
    lv_obj_set_align(ui_Heating, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Heating, "HEATING");
    ui_object_set_themeable_style_property(ui_Heating, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_PrimaryDisabled);
    ui_object_set_themeable_style_property(ui_Heating, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_PrimaryDisabled);
    lv_obj_set_style_text_font(ui_Heating, &ui_font_Ubuntu_Bold__45, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Flame = lv_image_create(ui_Main);
    lv_image_set_src(ui_Flame, &ui_img_flame_off_png);
    lv_obj_set_width(ui_Flame, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Flame, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Flame, -194);
    lv_obj_set_y(ui_Flame, 121);
    lv_obj_set_align(ui_Flame, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Flame, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Flame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_Seperator = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Main_Seperator, 3);
    lv_obj_set_height(ui_Main_Seperator, 242);
    lv_obj_set_x(ui_Main_Seperator, 14);
    lv_obj_set_y(ui_Main_Seperator, 0);
    lv_obj_set_align(ui_Main_Seperator, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Main_Seperator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Main_Seperator, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Main_Seperator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Primary);
    ui_object_set_themeable_style_property(ui_Main_Seperator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Primary);

    lv_obj_set_style_radius(ui_Main_Seperator, 40, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Main_Seperator, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Seperator, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Set_Temperature = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Set_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Set_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Set_Temperature, 127);
    lv_obj_set_y(ui_Set_Temperature, 6);
    lv_obj_set_align(ui_Set_Temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Set_Temperature, "89");
    ui_object_set_themeable_style_property(ui_Set_Temperature, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Primary);
    ui_object_set_themeable_style_property(ui_Set_Temperature, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Primary);
    lv_obj_set_style_text_font(ui_Set_Temperature, &ui_font_Ubuntu_Bold__75, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Down_Arrow = lv_image_create(ui_Main);
    lv_image_set_src(ui_Down_Arrow, &ui_img_down_arrow_png);
    lv_obj_set_width(ui_Down_Arrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Down_Arrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Down_Arrow, 125);
    lv_obj_set_y(ui_Down_Arrow, 93);
    lv_obj_set_align(ui_Down_Arrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Down_Arrow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Down_Arrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Panel2, 157);
    lv_obj_set_height(ui_Panel2, 3);
    lv_obj_set_x(ui_Panel2, 124);
    lv_obj_set_y(ui_Panel2, -43);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Primary);
    ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Primary);

    ui_Panel3 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Panel3, 157);
    lv_obj_set_height(ui_Panel3, 3);
    lv_obj_set_x(ui_Panel3, 124);
    lv_obj_set_y(ui_Panel3, 48);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Panel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Primary);
    ui_object_set_themeable_style_property(ui_Panel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Primary);

    ui_Temperature_F = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Temperature_F, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature_F, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature_F, -28);
    lv_obj_set_y(ui_Temperature_F, -86);
    lv_obj_set_align(ui_Temperature_F, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature_F, "°F");
    ui_object_set_themeable_style_property(ui_Temperature_F, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Primary);
    ui_object_set_themeable_style_property(ui_Temperature_F, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Primary);
    lv_obj_set_style_text_font(ui_Temperature_F, &ui_font_Ubuntu_Regular_45, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Set_Temperature_F = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Set_Temperature_F, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Set_Temperature_F, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Set_Temperature_F, 176);
    lv_obj_set_y(ui_Set_Temperature_F, -19);
    lv_obj_set_align(ui_Set_Temperature_F, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Set_Temperature_F, "°F");
    ui_object_set_themeable_style_property(ui_Set_Temperature_F, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Primary);
    ui_object_set_themeable_style_property(ui_Set_Temperature_F, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Primary);
    lv_obj_set_style_text_font(ui_Set_Temperature_F, &ui_font_Ubuntu_Regular__20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Up_Arrow = lv_image_create(ui_Main);
    lv_image_set_src(ui_Up_Arrow, &ui_img_up_arrow_png);
    lv_obj_set_width(ui_Up_Arrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Up_Arrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Up_Arrow, 125);
    lv_obj_set_y(ui_Up_Arrow, -86);
    lv_obj_set_align(ui_Up_Arrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Up_Arrow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Up_Arrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFi_Off = lv_image_create(ui_Main);
    lv_image_set_src(ui_WiFi_Off, &ui_img_wifi_off_png);
    lv_obj_set_width(ui_WiFi_Off, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFi_Off, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFi_Off, 206);
    lv_obj_set_y(ui_WiFi_Off, -138);
    lv_obj_set_align(ui_WiFi_Off, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFi_Off, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_WiFi_Off, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifi_On = lv_image_create(ui_Main);
    lv_image_set_src(ui_Wifi_On, &ui_img_wifi_png);
    lv_obj_set_width(ui_Wifi_On, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi_On, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifi_On, 206);
    lv_obj_set_y(ui_Wifi_On, -138);
    lv_obj_set_align(ui_Wifi_On, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Wifi_On, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Wifi_On, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Flame_On = lv_image_create(ui_Main);
    lv_image_set_src(ui_Flame_On, &ui_img_flame_png);
    lv_obj_set_width(ui_Flame_On, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Flame_On, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Flame_On, -194);
    lv_obj_set_y(ui_Flame_On, 121);
    lv_obj_set_align(ui_Flame_On, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Flame_On, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Flame_On, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Down_Arrow, ui_event_Down_Arrow, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Up_Arrow, ui_event_Up_Arrow, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_Temperature = NULL;
    ui_Humidity = NULL;
    ui_Heating = NULL;
    ui_Flame = NULL;
    ui_Main_Seperator = NULL;
    ui_Set_Temperature = NULL;
    ui_Down_Arrow = NULL;
    ui_Panel2 = NULL;
    ui_Panel3 = NULL;
    ui_Temperature_F = NULL;
    ui_Set_Temperature_F = NULL;
    ui_Up_Arrow = NULL;
    ui_WiFi_Off = NULL;
    ui_Wifi_On = NULL;
    ui_Flame_On = NULL;

}
