// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Thermostat_Controller

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_Heating;
extern lv_obj_t * ui_Flame;
extern lv_obj_t * ui_Main_Seperator;
extern lv_obj_t * ui_SetTemperature;
extern lv_obj_t * ui_DownArrow;
extern lv_obj_t * ui_UpDivider;
extern lv_obj_t * ui_DownDivider;
extern lv_obj_t * ui_Temperature_F;
extern lv_obj_t * ui_SetTemperature_F;
extern lv_obj_t * ui_UpArrow;
extern lv_obj_t * ui_WiFiOff;
extern lv_obj_t * ui_WifiOn;
extern lv_obj_t * ui_FlameOn;
extern void ui_event_UpTempTarget(lv_event_t * e);
extern lv_obj_t * ui_UpTempTarget;
extern void ui_event_DownTempTarget(lv_event_t * e);
extern lv_obj_t * ui_DownTempTarget;
extern lv_obj_t * ui_Settings;
extern void ui_event_SettingsTarget(lv_event_t * e);
extern lv_obj_t * ui_SettingsTarget;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

