// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Thermostat_Controller

#include "ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_Temperature = NULL;
lv_obj_t * ui_Humidity = NULL;
lv_obj_t * ui_Heating = NULL;
lv_obj_t * ui_Flame = NULL;
lv_obj_t * ui_Main_Seperator = NULL;
lv_obj_t * ui_SetTemperature = NULL;
lv_obj_t * ui_DownArrow = NULL;
lv_obj_t * ui_UpDivider = NULL;
lv_obj_t * ui_DownDivider = NULL;
lv_obj_t * ui_Temperature_F = NULL;
lv_obj_t * ui_SetTemperature_F = NULL;
lv_obj_t * ui_UpArrow = NULL;
lv_obj_t * ui_WiFiOff = NULL;
lv_obj_t * ui_WifiOn = NULL;
lv_obj_t * ui_FlameOn = NULL;
lv_obj_t * ui_UpTempTarget = NULL;
lv_obj_t * ui_DownTempTarget = NULL;
lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_SettingsTarget = NULL;
// event funtions
void ui_event_UpTempTarget(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        upTempEvent(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        upTempEvent(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        upTempEvent(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        upTempEventFinished(e);
    }
}

void ui_event_DownTempTarget(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        downTempEvent(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        downTempEvent(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        downTempEvent(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        downTempEventFinished(e);
    }
}

void ui_event_SettingsTarget(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_SettingsScreen_screen_init);
        initializeSettingsScreen(e);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_add_state(ui_Main, LV_STATE_PRESSED);       /// States
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x15233D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature, -125);
    lv_obj_set_y(ui_Temperature, -44);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature, "--");
    ui_object_set_themeable_style_property(ui_Temperature, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_PrimaryText);
    ui_object_set_themeable_style_property(ui_Temperature, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_PrimaryText);
    lv_obj_set_style_text_font(ui_Temperature, &ui_font_Ubuntu_Bold_180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidity, -109);
    lv_obj_set_y(ui_Humidity, 38);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humidity, "--% Humidity");
    ui_object_set_themeable_style_property(ui_Humidity, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_PrimaryText);
    ui_object_set_themeable_style_property(ui_Humidity, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_PrimaryText);
    lv_obj_set_style_text_font(ui_Humidity, &ui_font_Ubuntu_Bold__45, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Heating = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Heating, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Heating, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Heating, -101);
    lv_obj_set_y(ui_Heating, 124);
    lv_obj_set_align(ui_Heating, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Heating, "HEATING");
    ui_object_set_themeable_style_property(ui_Heating, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_PrimaryDisabled);
    ui_object_set_themeable_style_property(ui_Heating, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_PrimaryDisabled);
    lv_obj_set_style_text_font(ui_Heating, &ui_font_Ubuntu_Bold__45, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Flame = lv_image_create(ui_Main);
    lv_image_set_src(ui_Flame, &ui_img_flame_off_png);
    lv_obj_set_width(ui_Flame, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Flame, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Flame, -194);
    lv_obj_set_y(ui_Flame, 121);
    lv_obj_set_align(ui_Flame, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Flame, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Flame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_Seperator = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Main_Seperator, 3);
    lv_obj_set_height(ui_Main_Seperator, 242);
    lv_obj_set_x(ui_Main_Seperator, 14);
    lv_obj_set_y(ui_Main_Seperator, 0);
    lv_obj_set_align(ui_Main_Seperator, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Main_Seperator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Main_Seperator, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Main_Seperator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PrimaryText);
    ui_object_set_themeable_style_property(ui_Main_Seperator, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PrimaryText);

    lv_obj_set_style_radius(ui_Main_Seperator, 40, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Main_Seperator, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Seperator, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_SetTemperature = lv_label_create(ui_Main);
    lv_obj_set_width(ui_SetTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetTemperature, 127);
    lv_obj_set_y(ui_SetTemperature, 5);
    lv_obj_set_align(ui_SetTemperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetTemperature, "--");
    ui_object_set_themeable_style_property(ui_SetTemperature, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_PrimaryText);
    ui_object_set_themeable_style_property(ui_SetTemperature, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_PrimaryText);
    lv_obj_set_style_text_font(ui_SetTemperature, &ui_font_Ubuntu_Bold__75, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DownArrow = lv_image_create(ui_Main);
    lv_image_set_src(ui_DownArrow, &ui_img_down_arrow_png);
    lv_obj_set_width(ui_DownArrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DownArrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DownArrow, 125);
    lv_obj_set_y(ui_DownArrow, 86);
    lv_obj_set_align(ui_DownArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DownArrow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_DownArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UpDivider = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_UpDivider, 157);
    lv_obj_set_height(ui_UpDivider, 3);
    lv_obj_set_x(ui_UpDivider, 124);
    lv_obj_set_y(ui_UpDivider, -43);
    lv_obj_set_align(ui_UpDivider, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_UpDivider, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_UpDivider, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_UpDivider, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PrimaryText);
    ui_object_set_themeable_style_property(ui_UpDivider, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PrimaryText);

    ui_DownDivider = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_DownDivider, 157);
    lv_obj_set_height(ui_DownDivider, 3);
    lv_obj_set_x(ui_DownDivider, 124);
    lv_obj_set_y(ui_DownDivider, 43);
    lv_obj_set_align(ui_DownDivider, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DownDivider, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DownDivider, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_DownDivider, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PrimaryText);
    ui_object_set_themeable_style_property(ui_DownDivider, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PrimaryText);

    ui_Temperature_F = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Temperature_F, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature_F, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature_F, -18);
    lv_obj_set_y(ui_Temperature_F, -88);
    lv_obj_set_align(ui_Temperature_F, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature_F, "°F");
    ui_object_set_themeable_style_property(ui_Temperature_F, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_PrimaryText);
    ui_object_set_themeable_style_property(ui_Temperature_F, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_PrimaryText);
    lv_obj_set_style_text_font(ui_Temperature_F, &ui_font_Ubuntu_Regular_45, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTemperature_F = lv_label_create(ui_Main);
    lv_obj_set_width(ui_SetTemperature_F, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTemperature_F, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetTemperature_F, 182);
    lv_obj_set_y(ui_SetTemperature_F, -19);
    lv_obj_set_align(ui_SetTemperature_F, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetTemperature_F, "°F");
    ui_object_set_themeable_style_property(ui_SetTemperature_F, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_PrimaryText);
    ui_object_set_themeable_style_property(ui_SetTemperature_F, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_PrimaryText);
    lv_obj_set_style_text_font(ui_SetTemperature_F, &ui_font_Ubuntu_Regular__20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpArrow = lv_image_create(ui_Main);
    lv_image_set_src(ui_UpArrow, &ui_img_up_arrow_png);
    lv_obj_set_width(ui_UpArrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpArrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UpArrow, 125);
    lv_obj_set_y(ui_UpArrow, -86);
    lv_obj_set_align(ui_UpArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UpArrow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_UpArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiOff = lv_image_create(ui_Main);
    lv_image_set_src(ui_WiFiOff, &ui_img_wifi_off_png);
    lv_obj_set_width(ui_WiFiOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiOff, -15);
    lv_obj_set_y(ui_WiFiOff, 15);
    lv_obj_set_align(ui_WiFiOff, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_WiFiOff, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_WiFiOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiOn = lv_image_create(ui_Main);
    lv_image_set_src(ui_WifiOn, &ui_img_wifi_png);
    lv_obj_set_width(ui_WifiOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiOn, -15);
    lv_obj_set_y(ui_WifiOn, 15);
    lv_obj_set_align(ui_WifiOn, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_WifiOn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_WifiOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FlameOn = lv_image_create(ui_Main);
    lv_image_set_src(ui_FlameOn, &ui_img_flame_png);
    lv_obj_set_width(ui_FlameOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FlameOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FlameOn, -194);
    lv_obj_set_y(ui_FlameOn, 121);
    lv_obj_set_align(ui_FlameOn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FlameOn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_FlameOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UpTempTarget = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_UpTempTarget);
    lv_obj_set_width(ui_UpTempTarget, 185);
    lv_obj_set_height(ui_UpTempTarget, 110);
    lv_obj_set_x(ui_UpTempTarget, 125);
    lv_obj_set_y(ui_UpTempTarget, -70);
    lv_obj_set_align(ui_UpTempTarget, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_UpTempTarget, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DownTempTarget = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_DownTempTarget);
    lv_obj_set_width(ui_DownTempTarget, 185);
    lv_obj_set_height(ui_DownTempTarget, 110);
    lv_obj_set_x(ui_DownTempTarget, 125);
    lv_obj_set_y(ui_DownTempTarget, 75);
    lv_obj_set_align(ui_DownTempTarget, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DownTempTarget, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Settings = lv_image_create(ui_Main);
    lv_image_set_src(ui_Settings, &ui_img_gear_png);
    lv_obj_set_width(ui_Settings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Settings, 15);
    lv_obj_set_y(ui_Settings, 15);
    lv_obj_remove_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsTarget = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_SettingsTarget);
    lv_obj_set_width(ui_SettingsTarget, 100);
    lv_obj_set_height(ui_SettingsTarget, 66);
    lv_obj_remove_flag(ui_SettingsTarget, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_UpTempTarget, ui_event_UpTempTarget, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DownTempTarget, ui_event_DownTempTarget, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsTarget, ui_event_SettingsTarget, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_Temperature = NULL;
    ui_Humidity = NULL;
    ui_Heating = NULL;
    ui_Flame = NULL;
    ui_Main_Seperator = NULL;
    ui_SetTemperature = NULL;
    ui_DownArrow = NULL;
    ui_UpDivider = NULL;
    ui_DownDivider = NULL;
    ui_Temperature_F = NULL;
    ui_SetTemperature_F = NULL;
    ui_UpArrow = NULL;
    ui_WiFiOff = NULL;
    ui_WifiOn = NULL;
    ui_FlameOn = NULL;
    ui_UpTempTarget = NULL;
    ui_DownTempTarget = NULL;
    ui_Settings = NULL;
    ui_SettingsTarget = NULL;

}
