// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Thermostat_Controller

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_Heating;
extern lv_obj_t * ui_Flame;
extern lv_obj_t * ui_Main_Seperator;
extern lv_obj_t * ui_Set_Temperature;
extern void ui_event_Down_Arrow(lv_event_t * e);
extern lv_obj_t * ui_Down_Arrow;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Temperature_F;
extern lv_obj_t * ui_Set_Temperature_F;
extern void ui_event_Up_Arrow(lv_event_t * e);
extern lv_obj_t * ui_Up_Arrow;
extern lv_obj_t * ui_WiFi_Off;
extern lv_obj_t * ui_Wifi_On;
extern lv_obj_t * ui_Flame_On;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

