// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Thermostat_Controller

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScreen
extern void ui_SettingsScreen_screen_init(void);
extern void ui_SettingsScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_SettingsLabel;
extern lv_obj_t * ui_HeatLabel;
extern void ui_event_HeatOnSwitch(lv_event_t * e);
extern lv_obj_t * ui_HeatOnSwitch;
extern lv_obj_t * ui_HysteresisLabel;
extern void ui_event_HysteresisDropdown(lv_event_t * e);
extern lv_obj_t * ui_HysteresisDropdown;
extern lv_obj_t * ui_WiFiLabel;
extern lv_obj_t * ui_WiFiValue;
extern void ui_event_DoneButton(lv_event_t * e);
extern lv_obj_t * ui_DoneButton;
extern lv_obj_t * ui_DoneLabel;
extern lv_obj_t * ui_OnLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

