// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Thermostat_Controller

#include "ui.h"

lv_obj_t * ui_SettingsScreen = NULL;
lv_obj_t * ui_SettingsLabel = NULL;
lv_obj_t * ui_HeatLabel = NULL;
lv_obj_t * ui_HeatOnSwitch = NULL;
lv_obj_t * ui_HysteresisLabel = NULL;
lv_obj_t * ui_HysteresisDropdown = NULL;
lv_obj_t * ui_WiFiLabel = NULL;
lv_obj_t * ui_WiFiValue = NULL;
lv_obj_t * ui_DoneButton = NULL;
lv_obj_t * ui_DoneLabel = NULL;
lv_obj_t * ui_OnLabel = NULL;
// event funtions
void ui_event_HeatOnSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        heatValueChanged(e);
    }
}

void ui_event_HysteresisDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        hytersisValueChanged(e);
    }
}

void ui_event_DoneButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Main_screen_init);
    }
}

// build funtions

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x15233D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_SettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsLabel, 0);
    lv_obj_set_y(ui_SettingsLabel, -125);
    lv_obj_set_align(ui_SettingsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsLabel, "Settings");
    ui_object_set_themeable_style_property(ui_SettingsLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_PrimaryText);
    ui_object_set_themeable_style_property(ui_SettingsLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_PrimaryText);
    lv_obj_set_style_text_font(ui_SettingsLabel, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeatLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_HeatLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeatLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeatLabel, 24);
    lv_obj_set_y(ui_HeatLabel, 82);
    lv_label_set_text(ui_HeatLabel, "Heat On");
    ui_object_set_themeable_style_property(ui_HeatLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_SecondaryText);
    ui_object_set_themeable_style_property(ui_HeatLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_SecondaryText);
    lv_obj_set_style_text_font(ui_HeatLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeatOnSwitch = lv_switch_create(ui_SettingsScreen);
    lv_obj_set_width(ui_HeatOnSwitch, 50);
    lv_obj_set_height(ui_HeatOnSwitch, 30);
    lv_obj_set_x(ui_HeatOnSwitch, -50);
    lv_obj_set_y(ui_HeatOnSwitch, 82);
    lv_obj_set_align(ui_HeatOnSwitch, LV_ALIGN_TOP_RIGHT);

    ui_object_set_themeable_style_property(ui_HeatOnSwitch, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_HeatOnSwitch, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Border);

    ui_object_set_themeable_style_property(ui_HeatOnSwitch, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PrimaryAccent);
    ui_object_set_themeable_style_property(ui_HeatOnSwitch, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PrimaryAccent);

    ui_HysteresisLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_HysteresisLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HysteresisLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HysteresisLabel, 24);
    lv_obj_set_y(ui_HysteresisLabel, 140);
    lv_label_set_text(ui_HysteresisLabel, "Hysteresis");
    ui_object_set_themeable_style_property(ui_HysteresisLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_SecondaryText);
    ui_object_set_themeable_style_property(ui_HysteresisLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_SecondaryText);
    lv_obj_set_style_text_font(ui_HysteresisLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HysteresisDropdown = lv_dropdown_create(ui_SettingsScreen);
    lv_dropdown_set_options(ui_HysteresisDropdown, "  0°\n  1°\n  2°\n  3°");
    lv_obj_set_width(ui_HysteresisDropdown, 65);
    lv_obj_set_height(ui_HysteresisDropdown, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_HysteresisDropdown, -50);
    lv_obj_set_y(ui_HysteresisDropdown, 140);
    lv_obj_set_align(ui_HysteresisDropdown, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_HysteresisDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    ui_object_set_themeable_style_property(ui_HysteresisDropdown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_PrimaryText);
    ui_object_set_themeable_style_property(ui_HysteresisDropdown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_PrimaryText);
    lv_obj_set_style_text_font(ui_HysteresisDropdown, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_HysteresisDropdown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PrimaryAccent);
    ui_object_set_themeable_style_property(ui_HysteresisDropdown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PrimaryAccent);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_HysteresisDropdown), &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_WiFiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiLabel, 24);
    lv_obj_set_y(ui_WiFiLabel, 198);
    lv_label_set_text(ui_WiFiLabel, "WiFi");
    ui_object_set_themeable_style_property(ui_WiFiLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_SecondaryText);
    ui_object_set_themeable_style_property(ui_WiFiLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_SecondaryText);
    lv_obj_set_style_text_font(ui_WiFiLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiValue = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_WiFiValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiValue, -50);
    lv_obj_set_y(ui_WiFiValue, 198);
    lv_obj_set_align(ui_WiFiValue, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_WiFiValue, "");
    ui_object_set_themeable_style_property(ui_WiFiValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_SecondaryText);
    ui_object_set_themeable_style_property(ui_WiFiValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_SecondaryText);
    lv_obj_set_style_text_font(ui_WiFiValue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoneButton = lv_button_create(ui_SettingsScreen);
    lv_obj_set_width(ui_DoneButton, 100);
    lv_obj_set_height(ui_DoneButton, 50);
    lv_obj_set_x(ui_DoneButton, 0);
    lv_obj_set_y(ui_DoneButton, 110);
    lv_obj_set_align(ui_DoneButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DoneButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_DoneButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DoneButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DoneButton, lv_color_hex(0x00BFA5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DoneButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoneLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_DoneLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoneLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DoneLabel, 0);
    lv_obj_set_y(ui_DoneLabel, 110);
    lv_obj_set_align(ui_DoneLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoneLabel, "Done");
    ui_object_set_themeable_style_property(ui_DoneLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_PrimaryText);
    ui_object_set_themeable_style_property(ui_DoneLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_PrimaryText);
    lv_obj_set_style_text_font(ui_DoneLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_OnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnLabel, -53);
    lv_obj_set_y(ui_OnLabel, 113);
    lv_obj_set_align(ui_OnLabel, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_OnLabel, "On");
    ui_object_set_themeable_style_property(ui_OnLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_PrimaryText);
    ui_object_set_themeable_style_property(ui_OnLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_PrimaryText);
    lv_obj_set_style_text_decor(ui_OnLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OnLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HeatOnSwitch, ui_event_HeatOnSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HysteresisDropdown, ui_event_HysteresisDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DoneButton, ui_event_DoneButton, LV_EVENT_ALL, NULL);

}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

    // NULL screen variables
    ui_SettingsScreen = NULL;
    ui_SettingsLabel = NULL;
    ui_HeatLabel = NULL;
    ui_HeatOnSwitch = NULL;
    ui_HysteresisLabel = NULL;
    ui_HysteresisDropdown = NULL;
    ui_WiFiLabel = NULL;
    ui_WiFiValue = NULL;
    ui_DoneButton = NULL;
    ui_DoneLabel = NULL;
    ui_OnLabel = NULL;

}
